spring.application.name=Discools
server.port=5000

spring.datasource.url=jdbc:mysql://localhost:3306/discools?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=America/Sao_Paulo
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
